name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        python-version: ["3.7"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add requirements
      run: python -m pip install --upgrade wheel setuptools

    - name: Build and install
      run: pip install --verbose '.[test]'

    - name: Test
      run: python -m pytest tests

    - name: Lint with flake8
      run: |
        python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    
    - name: Lint with pylint
      run: |
        python -m pylint quine_mccluskey_tomas789
        
    - name: Check with black
      run: |
        python -m black --check quine_mccluskey_tomas789

